### PR TITLE
Stage 1: Refactor codebase (re)

### PR DESCRIPTION
**Pull request by mist8kengas**
The first stage of refactoring involves small changes[^1] to the codebase that shouldn't have any known bugs.

External extensive tests and code review are highly appreciated.

---

This PR also includes a contribution guide proposal.

[^1]: Small changes include but are not limited to: use better syntax, remove repetitive code, optimize statements.

### CODE REVIEW

**Comment by livingflore** [comment]
```md
[✅] automaticQuality
[✅] automaticTheaterMode
[✅] bottomButtons
[✅] buttonPlacement
[✅] customCSS
[✅] featureMenu
[✅] hideEndScreenCards
[✅] hideEndScreenCardsButton
[✅] hideLiveStreamChat
[✅] hideScrollbar
[✅] hideShorts
[✅] hideTranslateComment
[✅] importExportSettings
[✅] language
[✅] loopButton
[✅] maximizePlayerButton
[✅] onScreenDisplaySettings
[✅] openTranscriptButton
[✅] openYouTubeSettingsOnHover
[✅] pauseBackgroundPlayers
[✅] playbackSpeed
[✅] remainingTime
[✅] rememberLastVolume
[✅] removeRedirect
[✅] screenshotButton
[✅] scrollWheelSpeedControl
[✅] scrollWheelVolumeControl
[✅] shareShortener
[✅] shortsAutoScroll
[✅] skipContinueWatching
[✅] videoHistory
[✅] volumeBoost
[✅] youtubeDeepDark
```

**Review by mist8kengas — COMMENTED** [review]
## Git blame 20631b6305a404dd65726602192306215cb5aefd

Running `npm run format` changes these files, did you change the Prettier config and forgot to commit the changes? @livingflore

**Comment by VampireChicken12** [comment]
@mist8kengas it's late at night when I was working on merging changes from YouTube-Enhancer/extension/dev to mist8kengas/youtube-enhancer/dev and I accidentally merged it the wrong way it seems.

**Comment by mist8kengas** [comment]
> @mist8kengas it's late at night when I was working on merging changes from YouTube-Enhancer/extension/dev to mist8kengas/youtube-enhancer/dev and I accidentally merged it the wrong way it seems.

I can revert it

**Pull request merged**
